<?php
/**
 * Product schema generator.
 *
 * Generates Schema.org Product structured data from product catalog data
 * and mesh product analysis results.
 *
 * @package ShurlocSiteTools
 */

declare( strict_types=1 );

namespace Shurloc\SiteTools\Product\Generators;

use Shurloc\SiteTools\Product\Models\Catalog_Product_Entry;
use Shurloc\SiteTools\Product\Models\Mesh_Product_Result;

/**
 * Product schema generator.
 */
final class Product_Schema_Generator {

	/**
	 * Shur-loc Organization schema identifier.
	 *
	 * This matches the Organization node generated by Yoast.
	 *
	 * @var string
	 */
	private const ORGANIZATION_ID = 'https://shurloc.com/#organization';

	/**
	 * Generate Product schema data.
	 *
	 * @param Catalog_Product_Entry $product Product catalog entry.
	 * @param Mesh_Product_Result   $result  Mesh analysis result.
	 * @return array<string, mixed>
	 */
	public function generate(
		Catalog_Product_Entry $product,
		Mesh_Product_Result $result
	): array {

		$mesh_offers = array();

		foreach ( $result->mesh_variations as $variation ) {

			$entry = $variation['entry'];
			$spec  = $variation['spec'];

			$properties = array(
				array(
					'@type' => 'PropertyValue',
					'name'  => 'Mesh Count',
					'value' => $spec->get_mesh_count(),
				),
				array(
					'@type' => 'PropertyValue',
					'name'  => 'Thread Diameter',
					'value' => $spec->get_thread_diameter(),
				),
			);

			if ( null !== $spec->get_modifier() ) {

				$properties[] = array(
					'@type' => 'PropertyValue',
					'name'  => 'Modifier',
					'value' => $spec->get_modifier(),
				);
			}

			$properties[] = array(
				'@type' => 'PropertyValue',
				'name'  => 'Color',
				'value' => $spec->get_color(),
			);

			/*
			 * These offers are used internally to calculate the
			 * AggregateOffer values. They are not output individually.
			 */
			$mesh_offer = array(
				'@type'              => 'Offer',
				'priceCurrency'      => 'USD',
				'availability'       => 'https://schema.org/InStock',
				'name'               => $entry->variation,
				'additionalProperty' => $properties,
			);

			$price = $this->format_price(
				$entry->price
			);

			if ( null !== $price ) {
				$mesh_offer['price'] = $price;
			}

			$mesh_offers[] = $mesh_offer;
		}

		$schema = array(
			'@context'         => 'https://schema.org',
			'@type'            => 'Product',
			'@id'              => $product->product_url . '#product',
			'name'             => $product->product_name,
			'url'              => $product->product_url,
			'mainEntityOfPage' => array(
				'@id' => $product->product_url,
			),
		);

		/*
		 * Add SKU when available.
		 */
		if ( '' !== trim( $product->sku ) ) {

			$schema['sku'] = $product->sku;
		}

		/*
		 * Add product description when available.
		 */
		$description = trim(
			html_entity_decode(
				wp_strip_all_tags(
					$product->description
				)
			)
		);

		if ( '' !== $description ) {

			$schema['description'] = $description;
		}

		/*
		 * Add brand information.
		 */
		if ( null !== $product->brand ) {

			$schema['brand'] = array(
				'@type' => 'Brand',
				'name'  => $product->brand,
			);
		}

		/*
		 * Reference the Organization node generated by Yoast.
		 */
		$schema['manufacturer'] = $this->get_organization_reference();

		/*
		 * Add aggregate rating when reviews exist.
		 */
		if ( null !== $product->aggregate_rating ) {

			$schema['aggregateRating'] = $product->aggregate_rating;
		}

		/*
		 * Add reviews when available.
		 */
		if ( ! empty( $product->reviews ) ) {

			$schema['review'] = $product->reviews;
		}

		/*
		 * Products with mesh variations output one AggregateOffer.
		 * Simple products output one Offer.
		 */
		if ( ! empty( $mesh_offers ) ) {

			$schema['offers'] = $this->build_aggregate_offer(
				$mesh_offers
			);

		} elseif ( null !== $product->price ) {

			$schema['offers'] = $this->build_product_offer(
				$product
			);
		}

		/*
		 * Add product image when available.
		 */
		if ( null !== $product->image_url ) {

			$schema['image'] = $product->image_url;
		}

		return $schema;
	}

	/**
	 * Build simple product offer data.
	 *
	 * @param Catalog_Product_Entry $product Product catalog entry.
	 * @return array<string, mixed>
	 */
	private function build_product_offer(
		Catalog_Product_Entry $product
	): array {

		$offer = array(
			'@type'         => 'Offer',
			'priceCurrency' => 'USD',
			'availability'  => $product->availability,
			'url'           => $product->product_url,
			'seller'        => $this->get_organization_reference(),
		);

		$price = $this->format_price(
			$product->price
		);

		if ( null !== $price ) {
			$offer['price'] = $price;
		}

		return $offer;
	}

	/**
	 * Build aggregate offer data.
	 *
	 * The individual offers are used only to calculate the offer count
	 * and price range. They are not included in the generated schema.
	 *
	 * @param array<int, array<string, mixed>> $offers Product offers.
	 * @return array<string, mixed>
	 */
	private function build_aggregate_offer(
		array $offers
	): array {

		$prices = array();

		foreach ( $offers as $offer ) {

			if (
				isset( $offer['price'] )
				&& is_numeric( $offer['price'] )
			) {
				$prices[] = (float) $offer['price'];
			}
		}

		$aggregate_offer = array(
			'@type'         => 'AggregateOffer',
			'offerCount'    => count( $offers ),
			'priceCurrency' => 'USD',
			'availability'  => 'https://schema.org/InStock',
			'seller'        => $this->get_organization_reference(),
		);

		if ( ! empty( $prices ) ) {

			$aggregate_offer['lowPrice'] = $this->format_price(
				min( $prices )
			);

			$aggregate_offer['highPrice'] = $this->format_price(
				max( $prices )
			);
		}

		return $aggregate_offer;
	}

	/**
	 * Get a reference to the Shur-loc Organization schema node.
	 *
	 * @return array<string, string>
	 */
	private function get_organization_reference(): array {

		return array(
			'@id' => self::ORGANIZATION_ID,
		);
	}

	/**
	 * Format a price for schema output.
	 *
	 * @param float|null $price Price value.
	 * @return string|null
	 */
	private function format_price(
		?float $price
	): ?string {

		if ( null === $price ) {
			return null;
		}

		return number_format(
			$price,
			2,
			'.',
			''
		);
	}
}
